config/routes.rb
Rails.application.routes.draw do
  resources :images

  root 'images#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  after_create :set_width_height
  validates_presence_of :url
  validate :check_dimensions_by_url


  def check_dimensions
    if !image_cache.nil? && (image.width >= 500 || image.height >= 500)
      errors.add :image, "Dimension too big."
    end
  end

  def check_dimensions_by_url
    image = MiniMagick::Image.open(self.url)
    if image.width >= 500 || image.height >= 500
      errors.add :url, 'Dimensions are to big!'
    end
  end

  private

  def set_width_height
    width_height = MiniMagick::Image.open(self.url)

    self.width = width_height.width
    self.height = width_height.height
    self.image_type = width_height.type
    self.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.all.reverse
    unless @images.blank?
    @images.each do |i|
      @image_id = i.id
      @image_image_type = i.image_type
      @image_description = i.url
    end
    end
  end

  def new
    @image = Image.new

  end

  def create
    @image = Image.create(image_params)
    file = MiniMagick::Image.open("#{@image.url}")
    save_to_local = file.write("public/assets/image_#{@image.id}.#{file.type}")
    if @image.save
      save_to_local
      redirect_to root_path, notice: 'Image is successfully uploaded'
    else
      render :new
    end

  end

  def show
    @image = Image.find(params[:id])
  end

  def edit
    @image = Image.find(params[:id])
    @m = MiniMagick::Image.open("public/assets/image_#{@image.id}.#{@image.image_type}")
    @width =  @m.width
    @height = @m.height
  end

  def update
    @image = Image.find(params[:id])
    file = MiniMagick::Image.open("public/assets/image_#{@image.id}.#{@image.image_type}")
    @width = file.width
    @height = file.height
    if @image.update_attributes(image_params)
      file.resize("#{@image.width}x#{@image.height}")
      file.write("public/assets/image_#{@image.id}.#{@image.image_type}")
      redirect_to root_path, notice: 'Image was updated'
    else
      render :edit
    end

  end

  def destroy
    @image = Image.find(params[:id])

    @image.destroy
    redirect_to root_path, notice: 'Image was destroyed'
  end

  private

  def image_params
    params.require(:image).permit(:image, :width, :height, :image_type, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image, html: {class: 'form-horizontal image_form'} do |form| %>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <% if @image.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@image.errors.count, "errors") %></h2>
            <ul>
              <% @image.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    </div>

    <% unless @image.new_record? %>
       <%= image_tag("/assets/image_#{@image.id}.#{@image.image_type}", style: 'max-width: 375px; max-height: 500px')%>

        <%end %>
    <div class="col-xs-12 col-sm-12 col-md-8">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6">
          <%= form.label 'url' %>
          <%= form.text_field :url, placeholder: 'paste img url*', :class => "form-control paste_url", required: true  %>
        </div>

            <% unless @image.new_record?   %>
        <div class="col-xs-12 col-sm-12 col-md-6">
          <%= form.label 'Width' %>
          <%= form.text_field :width, value: @width %>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-6">
          <%= form.label 'Height' %>
          <%= form.text_field :height, value: @height %>
        </div>

            <%end %>

            <div class="submit_button">
              <%= form.submit  %>
            </div>


      </div>
    </div>
<% end %>

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/edit.html.erb
<%= render 'form' %>

app/views/images/index.html.erb
<html  manifest="/cache.manifest">
<div class="new_image">
  <%= link_to 'New Image', new_image_path %>
</div>
<table>
  <thead>
  <tr>
    <th>Url Image</th>
    <th>Image</th>
    <th>Width</th>
    <th>Height</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
      <%  @images.each do |image| %>
          <tr>
            <td><%= "public/assets/image_#{image.id}.#{image.image_type}" %></td>
            <td><%= image_tag("/assets/image_#{image.id}.#{image.image_type}", style: 'max-width: 375px; max-height: 500px')%></td>
            <td> <%= image.width%></td>
            <td><%= image.height %></td>
            <td>
              <ul class="actions">
                <li><%= link_to 'Edit', edit_image_path(image) %></li>
                <li><%= link_to 'Delete', image, method: :delete, data: { confirm: 'Are u sure?' } %></li>
              </ul>
            </td>
          </tr>
      <script type="text/javascript" charset="utf-8">

          localStorage.setItem("images_<%= image.id %>", "<%= ("#{request.url}public/assets/image_#{image.id}.#{image.image_type}")%>")
          localStorage.setItem("url<%= image.id %>", "<%= image.url %>")

      </script>

      <% end %>
  </tbody>
</table>
</html>

app/views/images/new.html.erb
<%= render partial:  'form', cached: true %>

app/views/images/show.html.erb
<%= image_tag("/assets/image_#{@image.id}.#{@image.image_type}", style: 'max-width: 375px; max-height: 500px')%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BevutaTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes"></head>

  <body>
    <%= yield %>
  </body>
</html>